import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionProvider from "@/components/SessionProvider"; // <-- import your session provider
import Navbar from "@/components/Navbar"; // optional, if you have a navbar

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the app with SessionProvider */}
        <SessionProvider>
          <Navbar /> {/* optional, if you have a navbar */}
          <main>
            <div className="section">
              <div className="container">{children}</div>
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}