import styles from "./page.module.css";
import Filters from "../components/Filters";
import Card from "../components/Card";

async function fetchTitles() {
  const response = await fetch(
    "https://web.ics.purdue.edu/~zong6/profile-app/get-titles.php",
    {
      next: { revalidate: 60 },
    }
  );

  const data = await response.json();
  return data ? data.titles : [];
}

async function getData({ title, search }) {
  const response = await fetch(
    `https://web.ics.purdue.edu/~zong6/profile-app/fetch-data-with-filter.php?title=${title}&name=${search}&limit=10`,
    {
      next: { revalidate: 60 },
    }
  );

  const data = await response.json();
  return data ? data.profiles : [];
}

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default async function Home({ searchParams }) {

  const params = await searchParams;

  const selectedTitle = params?.title || "";
  const selectedSearch = params?.search || "";

  const [titles, profiles] = await Promise.all([
    fetchTitles(),
    getData({ title: selectedTitle, search: selectedSearch }),
  ]);

  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <h1>Profile Directory</h1>

        <Filters
          titles={titles}
          title={selectedTitle}
          search={selectedSearch}
        />

        <div className={styles.grid}>
          {profiles
            ? profiles.map((profile) => (
                <Card key={profile.id} profile={profile} />
              ))
            : ""}
        </div>
      </main>
    </div>
  );
}


